---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - galeras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - galeras/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - galeras/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdatas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsmasqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsmasqs/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - dnsmasqs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - ipsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - ipsets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - ipsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - netconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - reservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - reservations/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - services/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.openstack.org
  resources:
  - redises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.openstack.org
  resources:
  - redises/finalizers
  verbs:
  - update
- apiGroups:
  - redis.openstack.org
  resources:
  - redises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
