---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrconfigurations
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - instanceha.openstack.org
  resources:
  - instancehas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - bgpconfigurations
  - dnsdata
  - dnsdatas
  - dnsmasqs
  - ipsets
  - reservations
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - bgpconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - bgpconfigurations/status
  - dnsdata/status
  - dnsmasqs/status
  - ipsets/status
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata/finalizers
  - dnsmasqs/finalizers
  - ipsets/finalizers
  - reservations/finalizers
  - services/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - netconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - rabbitmqs
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - rabbitmqs/finalizers
  - transporturls/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - rabbitmqs/status
  - transporturls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.openstack.org
  resources:
  - redises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.openstack.org
  resources:
  - redises/finalizers
  verbs:
  - update
- apiGroups:
  - redis.openstack.org
  resources:
  - redises/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - topology.openstack.org
  resources:
  - topologies
  verbs:
  - get
  - list
  - update
  - watch
