# permissions for end users to edit watchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher-editor-role
rules:
- apiGroups:
  - watcher.openstack.org
  resources:
  - watchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watchers/status
  verbs:
  - get
