apiVersion: mariadb.openstack.org/v1beta1
kind: MariaDBAccount
metadata:
  labels:
    app.kubernetes.io/name: mariadbaccount
    app.kubernetes.io/instance: mariadbaccount-sample
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mariadb-operator
    mariaDBDatabaseName: neutron
  name: neutron1
spec:
  userName: neutron1
  secret: neutrondb-secret

---

apiVersion: v1
data:
  # neutron123
  DatabasePassword: bmV1dHJvbjEyMw==
kind: Secret
metadata:
  name: neutrondb-secret
type: Opaque
